#!/bin/bash

set -ex

#wget https://apache.mirror.wearetriple.com/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
#tar -xzf spark-3.1.2-bin-hadoop3.2.tgz
#rm spark-3.1.2-bin-hadoop3.2.tgz

#yes | conda install -c conda-forge jupyterlab=2.1.2
#pip install jupyterlab-spark-ui-tab
#jupyter labextension install @acmore/jupyterlab-spark-ui-tab
#jupyter serverextension enable --py --sys-prefix spark-ui-tab

#jupyter labextension install jupyterlab_iframe@^0.2 --no-build
#jupyter lab build --dev-build=False --minimize=False
#jupyter serverextension enable --py jupyterlab_iframe

#mkdir -p ~/.jupyter
#echo -e $config > ~/.jupyter/jupyter_notebook_config.py

jupyter serverextension enable --sys-prefix jupyter_server_proxy
#jupyter labextension install jupyterlab-server-proxy
#jupyter serverextension enable --sys-prefix /home/jovyan/sparkUIserverextension

jupyter nbextension install sparkmonitor --py --user
jupyter nbextension enable  sparkmonitor --py --user
jupyter serverextension enable --py --user sparkmonitor # this should happen automatically
jupyter lab build --dev-build=False --minimize=False


