#!/bin/bash

wget https://apache.mirror.wearetriple.com/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
tar -xzf spark-3.1.2-bin-hadoop3.2.tgz
rm spark-3.1.2-bin-hadoop3.2.tgz

SPARK_HOME=$HOME/spark-3.1.2-bin-hadoop3.2
export PATH=$SPARK_HOME/bin:$PATH #this can be omitted

echo "y" | conda install -c conda-forge jupyterlab=2.1.2
pip install jupyterlab-spark-ui-tab
jupyter labextension install @acmore/jupyterlab-spark-ui-tab
jupyter serverextension enable --py --sys-prefix spark-ui-tab