#!/bin/bash

wget https://apache.mirror.wearetriple.com/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
tar -xzf spark-3.1.2-bin-hadoop3.2.tgz

#Tidy up
rm spark-3.1.2-bin-hadoop3.2.tgz

SPARK_HOME=$HOME/spark-3.1.2-bin-hadoop3.2

#Jupyter server proxy
#jupyter serverextension enable --sys-prefix jupyter_server_proxy
#jupyter labextension install jupyterlab_spark

pwd
ls

conda install -c conda-forge jupyterlab=2.1.2
#yes | npm i @jupyterlab/application@2.1.1
#yes | npm i @jupyterlab/apputils@2.1.1
#yes | npm i axios@0.18.0
#npm config set strict-ssl false
##npm install -g typescript@latest

yes | pip install jupyterlab-spark-ui-tab
yes | jupyter labextension install @s22s/jupyterlab-spark-ui-tab
yes | jupyter serverextension enable --py spark-ui-tab
#pip install --upgrade setuptools pip
##cd jupyterlab-spark-ui-tab
#pip install .
##npm install
#jupyter labextension install jupyterlab-spark-ui-tab
##jupyter serverextension enable --py spark-ui-tab
#jupyter labextension link .
#cd spark-ui-tab
#jupyter serverextension link .
##jupyter lab build