#!/bin/bash

SPARK_HOME=$HOME/spark-3.1.2-bin-hadoop3.2
export PATH=$SPARK_HOME/bin:$PATH #this can be omitted

git clone https://github.com/chrispyl/binder_content.git
mv /home/jovyan/binder_content/datasets /home/jovyan/binder_content/notebooks /home/jovyan/
rm -rf binder_content

exec "$@"
