#!/bin/bash

git clone https://github.com/chrispyl/binder_content.git
mv /home/jovyan/binder_content/datasets /home/jovyan/binder_content/notebooks /home/jovyan/
rm -rf binder_content

exec "$@"

cd notebooks