#!/bin/bash

ipython profile create
echo "c.InteractiveShellApp.extensions.append('sparkmonitor.kernelextension')" >>  $(ipython profile locate default)/ipython_kernel_config.py

git clone https://github.com/chrispyl/binder_content.git
mv /home/jovyan/binder_content/datasets /home/jovyan/binder_content/notebooks /home/jovyan/
rm -rf binder_content

jupyter trust /home/jovyan/notebooks/setup.ipynb
jupyter trust /home/jovyan/notebooks/dummy.ipynb

runipy /home/jovyan/notebooks/setup.ipynb

exec "$@"
